# Tugas 1

##Persiapan

###Import Modul

In [5]:
import pandas as pd
import math

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/FajarFatha/datamining/main/ds_salaries.csv")

In [7]:
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

## Proximity Measure for Nominal Attributes

In [1]:
def d1(i,j):
    P = 8
    M = 0
    for col in ["work_year", "experience_level", "employment_type","job_title","salary_currency","employee_residence","company_location","company_size"]:
        if df[col][i] == df[col][j]:
            M += 1

    return (P-M)/P

In [8]:
print(d1(1,2))
print(d1(1,3))
print(d1(1,4))

0.625
0.5
0.5

##Distance on Numeric Data: Minkowski Distance

In [9]:
def d2(i,j, h):
    result = 0
    for col in ["salary", "salary_in_usd","remote_ratio"]:
        result = math.pow(abs(df[col][i] - df[col][j]), h)
    return result**(1/h)

Manhattan distance

In [10]:
print(d2(1,2,1))
print(d2(1,3,1))
print(d2(1,4,1))

50.0
0.0
50.0

Euclidean distance

In [15]:
print(d2(1,2,2))
print(d2(1,3,2))
print(d2(1,4,2))

50.0
0.0
50.0

##Dissimiliarity

d(1,2)

In [12]:
print(d1(1,2)+d2(1,2,1))

50.625

d(1,3)

In [13]:
print(d1(1,3)+d2(1,3,1))

0.5

d(1,4)

In [14]:
print(d1(1,4)+d2(1,4,1))

50.5